package com.aiep.evaluacion.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DeparmentoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeparmentoAllPropertiesEquals(Deparmento expected, Deparmento actual) {
        assertDeparmentoAutoGeneratedPropertiesEquals(expected, actual);
        assertDeparmentoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeparmentoAllUpdatablePropertiesEquals(Deparmento expected, Deparmento actual) {
        assertDeparmentoUpdatableFieldsEquals(expected, actual);
        assertDeparmentoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeparmentoAutoGeneratedPropertiesEquals(Deparmento expected, Deparmento actual) {
        assertThat(expected)
            .as("Verify Deparmento auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeparmentoUpdatableFieldsEquals(Deparmento expected, Deparmento actual) {
        assertThat(expected)
            .as("Verify Deparmento relevant properties")
            .satisfies(e -> assertThat(e.getNombreDepartamento()).as("check nombreDepartamento").isEqualTo(actual.getNombreDepartamento()))
            .satisfies(e ->
                assertThat(e.getUbicacionDepartamento()).as("check ubicacionDepartamento").isEqualTo(actual.getUbicacionDepartamento())
            )
            .satisfies(e ->
                assertThat(e.getPresupuestoDepartamento())
                    .as("check presupuestoDepartamento")
                    .isEqualTo(actual.getPresupuestoDepartamento())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeparmentoUpdatableRelationshipsEquals(Deparmento expected, Deparmento actual) {
        // empty method
    }
}
